package name.kuznetsov.andrei.scoresightreading.model;

/**
 * Created by andrei on 9/24/16.
 */

public enum DurationsEnum {
    WHOLE_NOTE,
    DOTTED_HALF_NOTE,
    DOUBLE_DOTTED_HALF_NOTE,
    HALF_NOTE,
    HALF_NOTE_TRIPLET,
    QUARTER_NOTE,
    QUARTER_NOTE_TRIPLET,
    DOTTED_QUARTER_NOTE,
    DOUBLE_DOTTED_QUARTER_NOTE,
    EIGHTH_NOTE,
    DOTTED_EIGHTH_NOTE,
    EIGHTH_NOTE_TRIPLET,
    DOUBLE_DOTTED_EIGHTH_NOTE,
    SIXTEENTH_NOTE,
    DOTTED_SIXTEENTH_NOTE,
    SIXTEENTH_NOTE_TRIPLET,
    THIRTYSECOND_NOTE,
    THIRTYSECOND_NOTE_TRIPLET
}
